// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: mesh/v1/bus.proto

package meshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventBus_Publish_FullMethodName   = "/mesh.v1.EventBus/Publish"
	EventBus_Subscribe_FullMethodName = "/mesh.v1.EventBus/Subscribe"
)

// EventBusClient is the client API for EventBus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventBusClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (EventBus_PublishClient, error)
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (EventBus_SubscribeClient, error)
}

type eventBusClient struct {
	cc grpc.ClientConnInterface
}

func NewEventBusClient(cc grpc.ClientConnInterface) EventBusClient {
	return &eventBusClient{cc}
}

func (c *eventBusClient) Publish(ctx context.Context, opts ...grpc.CallOption) (EventBus_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventBus_ServiceDesc.Streams[0], EventBus_Publish_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &eventBusPublishClient{stream}
	return x, nil
}

type EventBus_PublishClient interface {
	Send(*BusIngressRequest) error
	Recv() (*BusIngressResponse, error)
	grpc.ClientStream
}

type eventBusPublishClient struct {
	grpc.ClientStream
}

func (x *eventBusPublishClient) Send(m *BusIngressRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventBusPublishClient) Recv() (*BusIngressResponse, error) {
	m := new(BusIngressResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventBusClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (EventBus_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventBus_ServiceDesc.Streams[1], EventBus_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &eventBusSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventBus_SubscribeClient interface {
	Recv() (*EventEnvelope, error)
	grpc.ClientStream
}

type eventBusSubscribeClient struct {
	grpc.ClientStream
}

func (x *eventBusSubscribeClient) Recv() (*EventEnvelope, error) {
	m := new(EventEnvelope)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventBusServer is the server API for EventBus service.
// All implementations must embed UnimplementedEventBusServer
// for forward compatibility
type EventBusServer interface {
	Publish(EventBus_PublishServer) error
	Subscribe(*SubscriptionRequest, EventBus_SubscribeServer) error
	mustEmbedUnimplementedEventBusServer()
}

// UnimplementedEventBusServer must be embedded to have forward compatible implementations.
type UnimplementedEventBusServer struct {
}

func (UnimplementedEventBusServer) Publish(EventBus_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedEventBusServer) Subscribe(*SubscriptionRequest, EventBus_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventBusServer) mustEmbedUnimplementedEventBusServer() {}

// UnsafeEventBusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventBusServer will
// result in compilation errors.
type UnsafeEventBusServer interface {
	mustEmbedUnimplementedEventBusServer()
}

func RegisterEventBusServer(s grpc.ServiceRegistrar, srv EventBusServer) {
	s.RegisterService(&EventBus_ServiceDesc, srv)
}

func _EventBus_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventBusServer).Publish(&eventBusPublishServer{stream})
}

type EventBus_PublishServer interface {
	Send(*BusIngressResponse) error
	Recv() (*BusIngressRequest, error)
	grpc.ServerStream
}

type eventBusPublishServer struct {
	grpc.ServerStream
}

func (x *eventBusPublishServer) Send(m *BusIngressResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventBusPublishServer) Recv() (*BusIngressRequest, error) {
	m := new(BusIngressRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EventBus_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventBusServer).Subscribe(m, &eventBusSubscribeServer{stream})
}

type EventBus_SubscribeServer interface {
	Send(*EventEnvelope) error
	grpc.ServerStream
}

type eventBusSubscribeServer struct {
	grpc.ServerStream
}

func (x *eventBusSubscribeServer) Send(m *EventEnvelope) error {
	return x.ServerStream.SendMsg(m)
}

// EventBus_ServiceDesc is the grpc.ServiceDesc for EventBus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventBus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mesh.v1.EventBus",
	HandlerType: (*EventBusServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _EventBus_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _EventBus_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mesh/v1/bus.proto",
}
