// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: mesh/v1/event.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Role    string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *AgentDescriptor) Reset() {
	*x = AgentDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_v1_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDescriptor) ProtoMessage() {}

func (x *AgentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_v1_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDescriptor.ProtoReflect.Descriptor instead.
func (*AgentDescriptor) Descriptor() ([]byte, []int) {
	return file_mesh_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *AgentDescriptor) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentDescriptor) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type TargetDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Scope   string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
}

func (x *TargetDescriptor) Reset() {
	*x = TargetDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_v1_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetDescriptor) ProtoMessage() {}

func (x *TargetDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_v1_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetDescriptor.ProtoReflect.Descriptor instead.
func (*TargetDescriptor) Descriptor() ([]byte, []int) {
	return file_mesh_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *TargetDescriptor) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TargetDescriptor) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type RuntimeContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeVersion string `protobuf:"bytes,1,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	InitkitVersion string `protobuf:"bytes,2,opt,name=initkit_version,json=initkitVersion,proto3" json:"initkit_version,omitempty"`
}

func (x *RuntimeContext) Reset() {
	*x = RuntimeContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_v1_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeContext) ProtoMessage() {}

func (x *RuntimeContext) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_v1_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeContext.ProtoReflect.Descriptor instead.
func (*RuntimeContext) Descriptor() ([]byte, []int) {
	return file_mesh_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeContext) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *RuntimeContext) GetInitkitVersion() string {
	if x != nil {
		return x.InitkitVersion
	}
	return ""
}

type EventEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId       string            `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string            `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventDomain   string            `protobuf:"bytes,3,opt,name=event_domain,json=eventDomain,proto3" json:"event_domain,omitempty"`
	SourceAgent   *AgentDescriptor  `protobuf:"bytes,4,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	Target        *TargetDescriptor `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Timestamp     string            `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CorrelationId string            `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte            `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     string            `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	Runtime       *RuntimeContext   `protobuf:"bytes,10,opt,name=runtime,proto3" json:"runtime,omitempty"`
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mesh_v1_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_v1_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_mesh_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetEventDomain() string {
	if x != nil {
		return x.EventDomain
	}
	return ""
}

func (x *EventEnvelope) GetSourceAgent() *AgentDescriptor {
	if x != nil {
		return x.SourceAgent
	}
	return nil
}

func (x *EventEnvelope) GetTarget() *TargetDescriptor {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EventEnvelope) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EventEnvelope) GetRuntime() *RuntimeContext {
	if x != nil {
		return x.Runtime
	}
	return nil
}

var File_mesh_v1_event_proto protoreflect.FileDescriptor

var file_mesh_v1_event_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x40,
	0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x22, 0x43, 0x0a, 0x10, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x62, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x6b, 0x69, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x6b,
	0x69, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x03, 0x0a, 0x0d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x3b, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52,
	0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x75, 0x78, 0x6f, 0x72, 0x67, 0x2f, 0x63,
	0x68, 0x75, 0x78, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x6d,
	0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mesh_v1_event_proto_rawDescOnce sync.Once
	file_mesh_v1_event_proto_rawDescData = file_mesh_v1_event_proto_rawDesc
)

func file_mesh_v1_event_proto_rawDescGZIP() []byte {
	file_mesh_v1_event_proto_rawDescOnce.Do(func() {
		file_mesh_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_mesh_v1_event_proto_rawDescData)
	})
	return file_mesh_v1_event_proto_rawDescData
}

var file_mesh_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mesh_v1_event_proto_goTypes = []interface{}{
	(*AgentDescriptor)(nil),  // 0: mesh.v1.AgentDescriptor
	(*TargetDescriptor)(nil), // 1: mesh.v1.TargetDescriptor
	(*RuntimeContext)(nil),   // 2: mesh.v1.RuntimeContext
	(*EventEnvelope)(nil),    // 3: mesh.v1.EventEnvelope
}
var file_mesh_v1_event_proto_depIdxs = []int32{
	0, // 0: mesh.v1.EventEnvelope.source_agent:type_name -> mesh.v1.AgentDescriptor
	1, // 1: mesh.v1.EventEnvelope.target:type_name -> mesh.v1.TargetDescriptor
	2, // 2: mesh.v1.EventEnvelope.runtime:type_name -> mesh.v1.RuntimeContext
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mesh_v1_event_proto_init() }
func file_mesh_v1_event_proto_init() {
	if File_mesh_v1_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mesh_v1_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_v1_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_v1_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mesh_v1_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mesh_v1_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_v1_event_proto_goTypes,
		DependencyIndexes: file_mesh_v1_event_proto_depIdxs,
		MessageInfos:      file_mesh_v1_event_proto_msgTypes,
	}.Build()
	File_mesh_v1_event_proto = out.File
	file_mesh_v1_event_proto_rawDesc = nil
	file_mesh_v1_event_proto_goTypes = nil
	file_mesh_v1_event_proto_depIdxs = nil
}
